---
# Variables for jenkins installation
  gossl_jenkins_repo: 'http://pkg.jenkins-ci.org/redhat/jenkins.repo'        # Jenkins repository
  gossl_jenkins_key: 'http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key'   # Jenkins key
  gossl_jenkins_key_local: '/root/ossl-ansible-cfg/cache/jenkins-ci.org.key' # Jenkins key - local copy
  jenkins_dependencies: # Jenkins dependencies
    - 'java-1.7.0-openjdk.x86_64'
