---
# ----------------------------------------------------------------------------
# (C) 2013, Marcin Praczko, <marcin.praczko@gmail.com>
#
# This file is part of OSSL-repeatme
#
# OSSL-repeatme is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OSSL-repeatme is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OSSL-repeatme. If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Variables for jenkins installation
# ----------------------------------------------------------------------------
gossl_jenkins_dest_dir: '/opt/jenkins'

gossl_jenkins:
  repo: 'http://pkg.jenkins-ci.org/redhat/jenkins.repo'            # Jenkins repository
  key: 'http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key'       # Jenkins key
  key_local: '/root/ossl-ansible-cfg/cache/jenkins-ci.org.key'     # Jenkins key - local copy
  dest_cli: '{{ gossl_jenkins_dest_dir }}/jenkins-cli.jar'         # Jenkins CLI destination
  dest_updates: '{{ gossl_jenkins_dest_dir }}updates_jenkins.json' # Jenkins updates file

  # Jenkins dependencies
  dependencies:
    - 'java-1.7.0-openjdk.x86_64'
