# -*- mode: ruby -*-
# vi: set ft=ruby :

# ----------------------------------------------------------------------------
# (C) 2013, Marcin Praczko, <marcin.praczko@gmail.com>
#
# This file is part of OSSL-repeatme
#
# OSSL-repeatme is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OSSL-repeatme is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OSSL-repeatme. If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# This vargant configuration is for:
# - Testing everything by using 2 VMs (Connections via LAN, services, etc)
#
# Vagrant box : Clean CentOS 6.4 x86_64
# Provisioning: Shell scripts
# ----------------------------------------------------------------------------

# Full documentation is available at:
# http://docs.vagrantup.com/v2/

Vagrant.configure("2") do |config|

  # VM - Testing VM01
  config.vm.define :vmtest01 do |vmtest01|
    vmtest01.vm.box = "ossl_centos64_x86_64_clean"

    # VagrantBox MD5 : b5f1ea8d83914c653da6a623b25b4c7f
    # VagrantBox SHA1: 65dadf6c7ae4ff6810b145bd68da0be5eacc9433
    vmtest01.vm.box_url = "http://www.silentlinux.info/vagrantbox/ossl_vagrant_centos_64_x86_64.box"
    vmtest01.vm.hostname = "ossl-test1"

    # --- Internal network only ---
    # This interface will be used for connecting with others VMs via internal
    # network
    vmtest01.vm.network :private_network, ip: "192.168.79.252"

    # --- Forwarding ports ---
    # HTTP / HTTPS
    vmtest01.vm.network :forwarded_port, guest: 80,   host: 20080
    vmtest01.vm.network :forwarded_port, guest: 443,  host: 20443

    # Jenkins
    vmtest01.vm.network :forwarded_port, guest: 8080, host: 28080

    # --- Basic provisioning ---
    # Run shell script
    vmtest01.vm.provision :shell, :path => "../../provisioning/shell/bootstrap-cacerts.sh"

  end

  # VM - Testing VM02
  config.vm.define :vmtest02 do |vmtest02|
    vmtest02.vm.box = "ossl_centos64_x86_64_clean"

    # VagrantBox MD5 : b5f1ea8d83914c653da6a623b25b4c7f
    # VagrantBox SHA1: 65dadf6c7ae4ff6810b145bd68da0be5eacc9433
    vmtest02.vm.box_url = "http://www.silentlinux.info/vagrantbox/ossl_vagrant_centos_64_x86_64.box"
    vmtest02.vm.hostname = "ossl-test2"

    # --- Internal network only ---
    # This interface will be used for connecting with others VMs via internal
    # network
    vmtest02.vm.network :private_network, ip: "192.168.79.253"

    # --- Forwarding ports ---
    # HTTP / HTTPS
    vmtest02.vm.network :forwarded_port, guest: 80,   host: 30080
    vmtest02.vm.network :forwarded_port, guest: 443,  host: 30443

    # Jenkins
    vmtest02.vm.network :forwarded_port, guest: 8080, host: 38080

    # --- Basic provisioning ---
    # Run shell script
    vmtest02.vm.provision :shell, :path => "../../provisioning/shell/bootstrap-cacerts.sh"

  end

end
