---
# ----------------------------------------------------------------------------
# (C) 2013, Marcin Praczko, <marcin.praczko@gmail.com>
#
# This file is part of OSSL-repeatme
#
# OSSL-repeatme is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OSSL-repeatme is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OSSL-repeatme. If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Playbook: Initial configuration for VM: ossl-console
# - Download Vagrant SSH Keys (this allows login to vagrant machines without password)
# Working with: ansible: 1.2
# ----------------------------------------------------------------------------

- name: OSSL-Console | Prepare VM for work with ansible and vagrant
  hosts: vms-ossl-console
  connection: local

  roles:
    - ossl-console-init

- name: OSSL-Console | Check access over SSH / SUDO to VM
  hosts: vms-ossl-console
  sudo: yes
  user: vagrant

  tasks:
  - name: OSSL-Console | Basic ping test
    ping:
