---
# Tasks: Install jenkins
# Working with: ansible: 1.2

- name: OSSL-Jenkins master | Install Jenkins dependencies
  yum: name={{ item }} state=present
  with_items: ${jenkins_dependencies}

- name: OSSL-Jenkins master | Intall Jenkins from yum repo
  yum: name=jenkins state=present

- name: OSSL-Jenkins master | Ensure Jenkins is running
  service: name=jenkins state=restarted
  register: jenkins_service
