---
# ----------------------------------------------------------------------------
# (C) 2013, Marcin Praczko, <marcin.praczko@gmail.com>
#
# This file is part of OSSL-repeatme
#
# OSSL-repeatme is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OSSL-repeatme is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OSSL-repeatme. If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Tasks: Install jenkins cli
# Working with: ansible: 1.2
# ----------------------------------------------------------------------------

# After installation or updating jenkins time is requried to run jenkins
# Jenkins can start quickly on port 8080 - but then jenkins need internally run engine
- name: OSSL-Jenkins cli | 90s delay while starting Jenkins
  wait_for: port=8080 delay=90
  when: jenkins_service.changed

# Create Jenkins CLI destination directory
- name: OSSL-Jenkins cli | Create Jenkins CLI destination directory
  file: path={{ gossl_jenkins.dest_dir }} state=directory

# Get Jenkins CLI from localhost
- name: OSSL-Jenkins cli | Get Jenkins CLI from localhost URL
  get_url: url=http://localhost:8080/jnlpJars/jenkins-cli.jar
    dest={{ gossl_jenkins.dest_cli }}
    mode=0440

# Get latest Jenkins update file
- name: OSSL-Jenkins cli | Get Jenkins updates
  get_url: url=http://updates.jenkins-ci.org/update-center.json
    dest={{ gossl_jenkins.dest_updates }} thirsty=yes mode=0440
  register: jenkins_updates

# Jenkins Update-center
- name: OSSL-Jenkins cli | Update-center Jenkins
  shell: "cat {{ gossl_jenkins.dest_updates }} | sed '1d;$d' | curl -X POST -H 'Accept: application/json' -d @- http://localhost:8080/updateCenter/byId/default/postBack"
  when: jenkins_updates.changed

# Install/update Jenkins plugins
- name: OSSL-Jenkins cli | Install/update plugins
  command: java -jar {{ gossl_jenkins.dest_cli }} -s http://localhost:8080 install-plugin {{ item }}
  with_items: "{{ gossl_jenkins_plugins }}"

# Wait for Jenkins to install plugins, assuming 60s should be sufficiant
- name: OSSL-Jenkins cli | 60s delay while installing plugins
  wait_for: port=8080 delay=60
  when: jenkins_updates.changed

# Safe-restart Jenkins
- name: OSSL-Jenkins cli | Safe-restart Jenkins
  command: java -jar {{ gossl_jenkins.dest_cli }} -s http://localhost:8080 safe-restart
  when: jenkins_updates.changed
  notify:
    - restart iptables
